# Generated by Django 6.0.1 on 2026-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
