# Generated by Django 6.0.1 on 2026-02-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_itemmenu_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='problema',
            field=models.TextField(blank=True, default=''),
        ),
    ]
