# Generated by Django 6.0.1 on 2026-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_pedido_problema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='nome',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('preparando', 'Preparando'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', '-criado_em'], name='menu_app_pe_status_511882_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['mesa', 'status'], name='menu_app_pe_mesa_eb70d4_idx'),
        ),
    ]
